export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const REQUEST_YOGUIS_PENDING = 'REQUEST_YOGUIS_PENDING';
export const REQUEST_YOGUIS_SUCCESS = 'REQUEST_YOGUIS_SUCCESS';
export const REQUEST_YOGUIS_FAILED = 'REQUEST_YOGUIS_FAILED';